# Generated by Django 5.2.3 on 2025-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='voucher_code',
            field=models.CharField(default='241f8f64', max_length=20, unique=True),
        ),
    ]
