# Generated by Django 5.2.3 on 2025-06-20 09:41

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_subscription_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='voucher_code',
            field=models.CharField(default=billing.models.generate_voucher_code, max_length=20, unique=True),
        ),
    ]
